address: '127.0.0.1'
port: 8000
workers: 32
keep_alive: 5
limits:
  bytes: 8192
  data-form: 2097152
  file: 1048576
  form: 32768
  json: 1048576
  msgpack: 1048576
  string: 8192
ident: Rocket
log_level: normal
shutdown:
  ctrlc: true
  grace: 2
  mercy: 3
  force: true
cli_colors: true
